resources:
  - name: ios-concourse
    type: git
    source:
      uri: https://github.com/tenten0213/ios-concourse.git
      branch: master
jobs:
  - name: build
    plan:
      - get: ios-concourse
        trigger: true
      - task: specs
        config:
          platform: darwin
          inputs:
            - name: ios-concourse
          run:
            path: bash
            args:
              - "-c"
              - "cd ios-concourse/ExampleForConcourse && bundle exec fastlane test"
