resources:
  - name: ios-concourse
    type: git
    source:
      uri: https://github.com/tenten0213/ios-concourse.git
      branch: master
jobs:
  - name: build
    plan:
      - get: ios-concourse
        trigger: true
      - task: specs
        config:
          platform: darwin
          inputs:
            - name: ios-concourse
          run:
            path: sh
            args:
              - -c
              - |
                env
                mkdir ios-concourse/ExampleForConcourse/Pods
                chown -R $SUDO_USER ios-concourse/
                chown -R $SUDO_USER ~/Library/Caches/CocoaPods
                chown -R $SUDO_USER ~/.cocoapods
                cd ios-concourse/ExampleForConcourse
                sudo -u $SUDO_USER bundle exec fastlane test
